# Generated by Django 3.2.16 on 2023-12-21 16:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bin_number', models.PositiveIntegerField(default=0)),
                ('gross_weight', models.PositiveIntegerField(default=0)),
                ('net_weight', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('supplier', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('initial', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PalletItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=60, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('pallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deliveries.pallet')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('supplier', models.CharField(max_length=60)),
                ('customer', models.CharField(max_length=60)),
                ('handpicked', models.BooleanField(default=False)),
                ('grapecode', models.CharField(max_length=20)),
                ('fruitCondition', models.CharField(max_length=1)),
                ('mog', models.PositiveIntegerField(default=0)),
                ('total_net_weight', models.PositiveIntegerField(default=0, editable=False)),
                ('total_gross_weight', models.PositiveIntegerField(default=0, editable=False)),
                ('tare', models.PositiveIntegerField(default=0, editable=False)),
                ('comments', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('user', models.CharField(max_length=10, null=True)),
                ('bins', models.ManyToManyField(to='deliveries.Bin')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
    ]
