# Generated by Django 3.2.16 on 2023-12-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=60)),
            ],
        ),
    ]
