# Generated by Django 3.2.16 on 2023-12-22 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_palletitem_grower'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='pallets', to='deliveries.PalletItem'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='status',
            field=models.CharField(default='Packed', max_length=10),
        ),
        migrations.AddField(
            model_name='pallet',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='pallet',
            name='user',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
