# Generated by Django 3.2.16 on 2024-02-22 11:22

from django.db import migrations

def set_autoincrement_start_value(apps, schema_editor):
    YourModel = apps.get_model('deliveries', 'Pallet')
    # Insert a new object with the desired ID
    max_id = 9999  # Your desired start value minus one
    YourModel.objects.create(id=max_id)
    # Delete the object
    YourModel.objects.filter(id=max_id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_pallet_start_time'),
    ]

    operations = [
        migrations.RunPython(set_autoincrement_start_value),
    ]
