version: '2'

services:
    app:
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
          - ./data:/data:rw
          - ./config:/config:ro
          - ./code:/code:rw
        ports:
          - "1880:1880"